### ISSUE TITLE
Picasso example?

### ISSUE THREAD

**Issue by dexcell** [Subito-it/Masaccio#1]
Any picasso example for this?

Thank you

**Comment by davide-maestroni** [comment]
The integration with Picasso should be quite straightforward. Basically it should consist in the implementation of a simple custom tranformation where the detection should happen.
Something like:

``` java
public class MasaccioTransformation implements Transformation {

  @Override 
  public Bitmap transform(Bitmap source) {
    MasaccioImageView.getFaceDetector().process(source);
    return source;
  }

  @Override
  public String key() { 
    return "masaccio()"; 
  }
}
```

Anyway, we may be adding further examples in the next days.

**Comment by dexcell** [comment]
Thank you for your reply :+1: 

Yeah, actually a short example like this in readme would be good enough for picasso  :)
